version: '3.8'

services:
  backend:
    build: ./backend
    container_name: examhub-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mssql+pyodbc://examhubadmin:ExamHub%402024!@examhub-sqlserver.database.windows.net/examhubdb?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes&Connect+Timeout=30
      - SECRET_KEY=examhub-super-secret-key-2024
    restart: always

  frontend:
    build: ./frontend
    container_name: examhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
