apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: examhub-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - examhub.centralus.cloudapp.azure.com
    secretName: examhub-tls-v3
  rules:
  - host: examhub.centralus.cloudapp.azure.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: examhub-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: examhub-frontend-service
            port:
              number: 80
